### ISSUE TITLE
User can make an account

### ISSUE THREAD

**Issue by shirokuma-cafe** [android102-spring23-group4/OwnCheff#9]
trying to decide what constitutes as an account

**TODO:**
- [x] Research google api for integrating sign-in
- [x] Make layout
- [x] Define User database schema if exists
- [x] Make sign in button
- [x] Define User Account information
- [x]  Make sign out button
- [x]  Display list of google accounts?

**NOTES**
made gmail account for app credentials
* email: owncheff@gmail.com
* pw: Verystrongpw1234!
* https://console.cloud.google.com/apis/credentials

**Schemas**
| User | | | | | | |
| - | - | - | - | - | - | - |
| `id` | `username : text` | `email : text` | `password_hashed : integer` | `role : integer` | `recipe list id : integer` | `settings id : blob` |

| Recipes | | | | |
| - | - | - | - | - |
| `id` | `recipe : text` | `is favorite : boolean` |  `have made : boolean` | `user id : integer` |

**FINDINGS**
```bat
rem command to get sha-1 hash for authentification
rem hash is project specific run in OwnCheff root
keytool -list -v -alias androiddebugkey -keystore %USERPROFILE%\.android\debug.keystore
```

**RESOURCES**
https://developers.google.com/identity/sign-in/android/sign-in
https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInAccount
https://console.cloud.google.com/apis/credentials
**Sign in error 10**
https://stackoverflow.com/questions/49450140/google-signin-api-exception-10
**For Changing Activities using intents**
https://guides.codepath.com/android/Using-Intents-to-Create-Flows
https://www.sqlite.org/datatype3.html
**Encryption**
https://developer.android.com/guide/topics/security/cryptography
https://developer.android.com/training/articles/keystore
https://guides.codepath.com/android/Storing-Secret-Keys-in-Android
